[package]
name = "marshal-rs-wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://github.com/savannstm/marshal-rs/tree/master/crates/marshal-rs-wasm"
keywords = ["marshal", "ruby", "wasm", "serialize", "deserialize"]
publish = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory"]

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
marshal-rs = { path = "../..", default-features = false, features = [
    "alloc",
    "serde",
] }
serde = "1.0.229"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "=0.2.127"

[dev-dependencies]
wasm-bindgen-test = "0.3.77"
