[package]
name = "marshal-rs-capi"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://github.com/savannstm/marshal-rs/tree/master/crates/marshal-rs-capi"
publish = false

[package.metadata.capi.header]
name = "marshal"
subdirectory = false
# Generation is disabled to not generate a header
# using cbindgen, we provide a header ourselves
generation = false

[package.metadata.capi.pkg_config]
name = "marshal-rs"
filename = "marshal-rs"

[package.metadata.capi.library]
name = "marshal_rs"

[lib]
name = "marshal_rs"
crate-type = ["rlib", "cdylib", "staticlib"]
doctest = false

[features]
default = ["std"]
std = ["marshal-rs/std"]
capi = []

[dependencies]
marshal-rs = { path = "../..", default-features = false, features = ["alloc"] }
